# Generated by Django 4.2 on 2026-05-05 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="resources/")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="resources/images/"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("presentation", "Presentation"),
                            ("worksheet", "Worksheet"),
                            ("activity", "Activity"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
