# Generated by Django 4.2 on 2026-05-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0004_resource"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resource",
            name="image",
        ),
        migrations.AlterField(
            model_name="resource",
            name="category",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
