# Generated by Django 4.2 on 2026-05-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0005_remove_resource_image_alter_resource_category"),
    ]

    operations = [
        migrations.DeleteModel(
            name="pdfFile",
        ),
        migrations.AlterModelOptions(
            name="resource",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Resource",
                "verbose_name_plural": "Resources",
            },
        ),
        migrations.AddField(
            model_name="resource",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="download_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="resource",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="resources/images/"
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="category",
            field=models.CharField(
                choices=[
                    ("presentation", "Presentation"),
                    ("worksheet", "Worksheet"),
                    ("activity", "Activity"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="file",
            field=models.FileField(upload_to="resources/files/"),
        ),
    ]
