# Generated by Django 4.2 on 2026-06-08 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0007_resourcedownload"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="resourcedownload",
            options={},
        ),
        migrations.AddField(
            model_name="resource",
            name="activity_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("lesson", "Lesson"),
                    ("abc", "ABC"),
                    ("show_me", "Show Me"),
                    ("answer_grid", "Answer Grid"),
                    ("answer_maze", "Answer Maze"),
                    ("create_question", "Create Question"),
                    ("digit_puzzle", "Digit Puzzle"),
                    ("four_in_row", "Four In Row"),
                    ("link", "Link"),
                    ("true_false_maze", "True False Maze"),
                    ("worded", "Worded"),
                    ("card_match", "Card Match"),
                    ("card_sort", "Card Sort"),
                    ("messenger", "Messenger"),
                    ("relay_race", "Relay Race"),
                    ("treasure_trail", "Treasure Trail"),
                    ("three_stars", "3 Stars"),
                    ("bingo", "Bingo"),
                    ("blockbusters", "Blockbusters"),
                    ("car_race", "Car Race"),
                    ("noughts_crosses", "Noughts & Crosses"),
                    ("penalty_shootout", "Penalty Shootout"),
                    ("shootout", "Shootout"),
                    ("splat", "Splat"),
                    ("yes_no_maybe", "Yes No Maybe"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("easy", "Easy"),
                    ("medium", "Medium"),
                    ("hard", "Hard"),
                    ("challenge", "Challenge"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="learning_goal",
            field=models.CharField(
                blank=True,
                choices=[
                    ("presentation", "Сабактын презентациясы"),
                    ("patterns", "Мыйзамченемдүүлүктөр"),
                    ("visuals", "Визуалдык түшүнүү"),
                    ("discussion", "Математикалык талкуу"),
                    ("discovery", "Изилдөө жана ачылыш"),
                    ("fluency", "Машыгуу жана флюенттүүлүк"),
                    ("retrieval", "Кайталоо жана эстеп калуу"),
                    ("problem_solving", "Маселе чечүү"),
                    ("modelling", "Турмушта колдонуу"),
                    ("proof", "Далилдөө жана негиздөө"),
                    ("games", "Оюндар"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resources",
                to="personal.topic",
            ),
        ),
    ]
