# Generated by Django 4.2 on 2026-06-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0009_subtopic_resource_subtopic"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subtopic",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="topic",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="subtopic",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="topic",
            name="icon",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="topic",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
