# Generated by Django 4.2 on 2026-06-09 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0010_alter_subtopic_options_alter_topic_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubSubtopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField()),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "subtopic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsubtopics",
                        to="personal.subtopic",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
