# Generated by Django 4.2 on 2026-06-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0012_menuitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
