# Generated by Django 4.2 on 2026-09-16 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0013_menuitem_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resourcedownload",
            options={
                "ordering": ["-downloaded_at"],
                "verbose_name": "Download Log",
                "verbose_name_plural": "Download Logs",
            },
        ),
    ]
