# Generated by Django 4.2 on 2026-09-20 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0017_loginevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="subsubtopic",
            field=models.ForeignKey(
                blank=True,
                help_text="Must belong to the Subtopic selected above.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="menu_items",
                to="personal.subsubtopic",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="subtopic",
            field=models.ForeignKey(
                blank=True,
                help_text="Must belong to the Topic selected above.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="menu_items",
                to="personal.subtopic",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                help_text="Links to this topic's page. Leave Subtopic/Sub-subtopic blank for a topic-level link.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="menu_items",
                to="personal.topic",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="url_name",
            field=models.CharField(
                blank=True,
                help_text="Only for a fixed, argument-less page (e.g. 'directed_numbers'). To link to a topic/subtopic/sub-subtopic page, use the Topic/Subtopic/Sub-subtopic fields below instead - they take priority over this one when set.",
                max_length=200,
                null=True,
            ),
        ),
    ]
