# Generated by Django 4.2 on 2026-09-20 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0018_menuitem_subsubtopic_menuitem_subtopic_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="subsubtopic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resources",
                to="personal.subsubtopic",
            ),
        ),
    ]
