# Generated by Django 4.2 on 2026-09-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0019_resource_subsubtopic"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "body",
                    models.TextField(
                        help_text="Кыска түшүндүрмө - эмне өзгөрдү же кошулду."
                    ),
                ),
                ("published_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Жаңылык",
                "verbose_name_plural": "Жаңылыктар",
                "ordering": ["-published_date", "-created_at"],
            },
        ),
    ]
