# Generated by Django 4.2 on 2026-09-22 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0020_exams_and_questions"),
        ("personal", "0021_newspost"),
    ]

    operations = []
