# Generated by Django 4.2 on 2026-10-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0020_newspost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="category",
            field=models.CharField(
                choices=[
                    ("presentation", "Презентация"),
                    ("worksheet", "Иш барак"),
                    ("activity", "Мугалим жетектеген ишмердик"),
                ],
                max_length=50,
            ),
        ),
    ]
