# Generated by Django 4.2 on 2026-02-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_account_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="DownloadFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="downloads/")),
                ("download_count", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
