# Generated by Django 4.2 on 2026-05-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_downloadfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="subscription_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="downloadfile",
            name="last_downloaded",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="downloadfile",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="downloadfile",
            name="download_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
