# Generated by Django 4.2 on 2026-09-15 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_account_subscription_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last_login"
            ),
        ),
    ]
