# Generated by Django 4.2 on 2026-09-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_paymentqrcode_subscriptionrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentqrcode",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Эгер сүрөт жүктөбөсөңүз, ушул жерге төлөм шилтемесин коюңуз - QR код автоматтык түрдө түзүлөт.",
                verbose_name="Төлөм шилтемеси (Finik.kg ж.б.)",
            ),
        ),
        migrations.AlterField(
            model_name="paymentqrcode",
            name="image",
            field=models.ImageField(blank=True, upload_to="payment_qr/"),
        ),
    ]
