# Generated by Django 4.2 on 2026-09-17 15:37

import config.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_paymentqrcode_link_alter_paymentqrcode_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentqrcode",
            name="image",
            field=models.ImageField(
                blank=True,
                storage=config.storage_backends.persistent_media_storage,
                upload_to="payment_qr/",
            ),
        ),
    ]
