# Generated by Django 4.2 on 2026-09-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_alter_paymentqrcode_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionrequest",
            name="activated_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="subscriptionrequest",
            name="plan",
            field=models.CharField(
                choices=[
                    ("3m", "3 ай - 1499 сом"),
                    ("6m", "6 ай - 2999 сом"),
                    ("1y", "1 жыл - 4999 сом"),
                ],
                max_length=2,
            ),
        ),
    ]
