# Generated by Django 4.2 on 2026-09-22 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0009_subscriptionrequest_activated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Мектептин аталышы"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Мектеп",
                "verbose_name_plural": "Мектептер",
            },
        ),
        migrations.AddField(
            model_name="account",
            name="is_school_admin",
            field=models.BooleanField(
                default=False,
                help_text="Мектептин башкаруучусу - өз мектебиндеги мугалимдерди көзөмөлдөй жана башкара алат.",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teachers",
                to="account.school",
            ),
        ),
    ]
