# Generated by Django 4.2 on 2026-10-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0009_subscriptionrequest_activated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="current_plan",
            field=models.CharField(
                blank=True,
                choices=[
                    ("3m", "3 ай - 1499 сом"),
                    ("6m", "6 ай - 2999 сом"),
                    ("1y", "1 жыл - 4999 сом"),
                ],
                help_text="Акыркы ырасталган төлөм планы. Акы төлөнбөгөн аккаунттар үчүн бош (сыноо мөөнөтү).",
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="trial_days",
            field=models.PositiveIntegerField(
                default=7,
                help_text="Акысыз сыноо мөөнөтү (күн). Катталган күндөн тартып эсептелет (subscription_end коюлбаса).",
            ),
        ),
    ]
