# Generated by Django 4.2 on 2026-10-06 06:17

from django.db import migrations


def backfill_trial_days(apps, schema_editor):
    Account = apps.get_model('account', 'Account')
    Account.objects.update(trial_days=365)


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0011_account_current_plan_account_trial_days"),
    ]

    operations = [
        migrations.RunPython(backfill_trial_days, migrations.RunPython.noop),
    ]
