# Generated by Django 4.2 on 2026-10-06 06:35

from django.db import migrations

from apps.account.migration_utils import backfill_current_plan


def _backfill_current_plan(apps, schema_editor):
    Account = apps.get_model('account', 'Account')
    backfill_current_plan(Account)


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0012_backfill_trial_days"),
    ]

    operations = [
        migrations.RunPython(_backfill_current_plan, migrations.RunPython.noop),
    ]
